### ISSUE TITLE
Segfault on mixed line endings

### ISSUE THREAD

**Issue by stasoid** [adyxax/nimfunge98#1]
(Tested on Windows)
~~~
>xxd tst
00000000: 400a 0d0a                                @...
>nimfunge98 tst
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
~~~

**Comment by adyxax** [comment]
This bug has been fixed, thank you.

I would appreciate if you could please confirm it is all good for you too.

**Comment by stasoid** [comment]
Oh, yes. Now I don't have to remember to make second line nonempty so it doesn't segfault (I have a lot of programs with empty second line). Thank you.

**Comment by adyxax** [comment]
Might I ask what you are working on that made you try out my interpreters? It is rare to meet a fellow Befunge artist^^

**Comment by stasoid** [comment]
I am not an artist unfortunately, I am a hoarder. 
I hoard languages (and their implementations) into [this polyglot](https://codegolf.stackexchange.com/questions/102370/add-a-language-to-a-polyglot).
Added a bunch of Befunge-98 interpreters [recently](https://codegolf.stackexchange.com/a/250487), but none of yours yet (currently working on it).
The programs I mentioned are little tests that help me understand how to distinguish between different interpreters.

**Comment by adyxax** [comment]
Damn, this is a whole over level of craziness! You have my respects sir!
